lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuesta/', include('encuesta.urls')),
    path('tarea/', include('tarea.urls')),
]

lab02/tarea/urls.py
from django.urls import path

from . import views

app_name = 'tarea'

urlpatterns = [
    path('operacion', views.formularioOperaciones, name='formularioOperaciones'),
    path('operacion/resultado', views.calcularOperacion, name='operaciones'),
    path('cilindro', views.formularioCilindro, name='formularioCilindro'),
    path('cilindro/resultado', views.calcularCilindro, name='cilindro'),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/tarea/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render

def index(request):
    context = {
        'titulo' : 'Formulario',
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo' : "Respuesta",
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/tarea/views.py
from django.shortcuts import render
import math

def formularioOperaciones(request):
    context = {
        'titulo' : 'Formulario',
    }
    return render(request, 'tarea/operaciones.html', context)

def calcularOperacion(request):
    valor1 = int(request.POST['valor1'])
    valor2 = int(request.POST['valor2'])
    operacion = request.POST['operacion']
    print (operacion)
    if (operacion=="suma"):
        respuesta = valor1 + valor2
        signo = "+"
    if (operacion=="resta"):
        respuesta = valor1 - valor2
        signo = "-"
    if (operacion=="multiplicacion"):
        respuesta = valor1 * valor2
        signo = "*"
    context = {
        'titulo' : "Respuesta",
        'valor1' : request.POST['valor1'],
        'valor2' : request.POST['valor2'],
        'operacion' : signo,
        'respuesta' : respuesta
    }
    return render(request, 'tarea/resultadoOperaciones.html', context)

def formularioCilindro(request):
    context = {
        'titulo' : 'CALCULO DEL VOLUMEN DE UN CILINDRO',
    }
    return render(request, 'tarea/cilindro.html', context)

def calcularCilindro(request):
    diametro = float(request.POST['diametro'])
    altura = float(request.POST['altura'])
    volumen = math.pi*((diametro/2)**2)*altura
    context = {
        'titulo' : "Respuesta",
        'volumen' : volumen,
    }
    return render(request, 'tarea/resultadoCilindro.html', context)

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Education:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatorio" selected="selected">Educación Obligatoria</option>
        <option value="formacion-profesional">Formación Profesional</option>
        <option value="universidad">Universidad</option>
    </select> <br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles">Inglés</input>
    <input type="checkbox" name="idiomas" value="frances">Frances</input>
    <input type="checkbox" name="idiomas" value="aleman">Alemán</input><br>
    Email:
    <input tpye="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    // Boton de enviar
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{titulo}}</h2>
<p>Nombre : {{ nombre }}</p>
<p>Clave : {{ clave }}</p>
<p>Educación : {{ educacion }}</p>
<p>Nacionalidad : {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email : {{ correo }}</p>
<p>Sitio web: {{ website }}</p>

lab02/tarea/templates/tarea/cilindro.html
<h2>{{ titulo }}</h2>
<form action="{% url 'tarea:cilindro' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros:
    <input type="text" name="diametro"><br>
    Introduzca la altura en metros:
    <input type="text" name="altura"><br>
    <input type="submit" name="submit" value="Calcular">
</form>

lab02/tarea/templates/tarea/operaciones.html
<h2>{{ titulo }}</h2>
<form action="{% url 'tarea:operaciones' %}" method="post">
    {% csrf_token %}
    Valor 1:
    <input type="text" name="valor1"><br>
    Valor 2:
    <input type="text" name="valor2"><br>
    Operacion:
    <select name="operacion">
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicacion</option>
    </select> <br>
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/tarea/templates/tarea/resultadoCilindro.html
<h2>{{titulo}}</h2>
<p>El volumen del cilindro es de {{volumen}} metros cubicos</p>

lab02/tarea/templates/tarea/resultadoOperaciones.html
<h2>{{titulo}}</h2>
<p>Resultado : {{ valor1 }} {{operacion}} {{valor2}} = {{respuesta}}</p>